### ISSUE TITLE
Could not find a package configuration file provided by "vpi"

### ISSUE THREAD

**Issue by ArghyaChatterjee** [NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation#17]
Hello,

I am trying this repository outside docker. I have a laptop with ubuntu 22.04 and ros humble version installed. I am having the following issue:
```
arghya@arghya-Pulse-GL66-12UEK:~/isaac_ros_pose_estimation_ws$ colcon build --symlink-install
Starting >>> isaac_ros_common
Starting >>> isaac_ros_test
--- stderr: isaac_ros_common                                                              
CMake Error at CMakeLists.txt:22 (find_package):
  By not providing "Findvpi.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "vpi", but
  CMake did not find one.

  Could not find a package configuration file provided by "vpi" with any of
  the following names:

    vpiConfig.cmake
    vpi-config.cmake

  Add the installation prefix of "vpi" to CMAKE_PREFIX_PATH or set "vpi_DIR"
  to a directory containing one of the above files.  If "vpi" provides a
  separate development package or SDK, be sure it has been installed.


---
Failed   <<< isaac_ros_common [0.39s, exited with code 1]
Aborted  <<< isaac_ros_test [0.59s]                      
                                 
Summary: 0 packages finished [0.74s]
  1 package failed: isaac_ros_common
  1 package aborted: isaac_ros_test
  2 packages had stderr output: isaac_ros_common isaac_ros_test
  30 packages not processed
```
When I tried to install libnvvpi2, it also can't find it. Is this vpi part of jetson family ?
```
arghya@arghya-Pulse-GL66-12UEK:~/isaac_ros_pose_estimation_ws$ sudo apt-get install libnvvpi2
[sudo] password for arghya: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libnvvpi2
```
What should I do now ?

**Comment by jaiveersinghNV** [comment]
Are you running this inside the Isaac ROS Docker container started using `run_dev.sh` from Isaac ROS Common? That Docker container will have all of the dependencies you need, including VPI.

If you choose not to run Isaac ROS inside the container, you will need to manually install the VPI debians using the steps [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/Dockerfile.x86_64#L129), along with all of the other dependencies that are automatically installed in that Dockerfile.

On x86, VPI must be installed manually, but on Jetson, VPI can be automatically installed by the SDK Manager during the initial device flash process.

**Comment by Kamlesh364** [comment]
@jaiveersinghNV 
I am facing the same issue while running inside the ISAAC ROS Docker container using `run_dev.sh`.  I am doing this on Jetson TX2 board.

**Comment by breaker-mm** [comment]
> @jaiveersinghNV I am facing the same issue while running inside the ISAAC ROS Docker container using `run_dev.sh`. I am doing this on Jetson TX2 board.

I've met this problem on Jetson Orin NX board before (in the Isaac Ros Docker container). try this, maybe you just lost some packages.
```bash
   sudo apt intall libnvvpi2 vpi2-dev
   ```
