### ISSUE TITLE
Failed to builed base image

### ISSUE THREAD

**Issue by JojoSim0n** [NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation#18]
after following the steps in Quickstart, i get the error : Failed to build base image
its seems to result from insufficient authorization rights
![Bildschirmfoto_2023-04-28_12-37-55](https://user-images.githubusercontent.com/82467188/235125932-16fa6e87-9726-4621-a1c0-3e693188a914.png)

**Comment by jaiveersinghNV** [comment]
Thanks for reporting this issue. We're still looking into it, but we have a workaround to get you unblocked.

Could you please try the steps detailed in [this comment](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/issues/82#issuecomment-1520944262)? Specifically, please try registering for an NGC account and then retrying this step. Once authorized with NGC, you should no longer see the 401 error.

**Comment by JojoSim0n** [comment]
I did the NGC account thingy and everything worked properly, thanks
