### ISSUE TITLE
How to use this ros_pose_estimation package with realsense D435/D415 camera.

### ISSUE THREAD

**Issue by Avi241** [NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation#20]
Thanks you for this great contribution. I would like to know how we can use dope pose estimation with realsense D435i/D415 camera, how to build the realsense package in docker container and what all necessary changes are required. 
It will be really helpful if someone can help me with this.

**Comment by jaiveersinghNV** [comment]
Have you had the chance to work through the [Quickstart](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation/tree/main#quickstart) yet? This quickstart will ensure that you can run the DOPE pose estimation node inside your Isaac ROS development environment.

Then, you can use the tutorial [here](https://github.com/NVIDIA-ISAAC-ROS/.github/blob/main/profile/realsense-setup.md) to add RealSense support inside your container. The DOPE quickstart uses images that are fed in from a sample rosbag; simply replace this input topic with one of the camera feeds on your RealSense camera, and you should start seeing estimated poses.

If you encounter any specific issues along the way, please describe them in this thread and we'll be happy to help you.
