### ISSUE TITLE
DOPE network is not detecting training objects with real world images

### ISSUE THREAD

**Issue by Maxime-Syc** [NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation#21]
Hello everyone,

I am trying to develop a real world application utilizing the DOPE network. From my understanding, each of the 40 models can only detect one type of object each.

I am using a RealSense D435 as a camera and remapped the color/image_raw topic to /image so the DOPE network could access it and the image resolution was set to 640x480 at 30 fps.

The objects are laid on a white background with the camera 60.5 cm above, looking straight down.

I have 5 objects from the training data set (Heinz ketchup bottle, French mustard bottle, Campbells' tomato soup can and Cheez'in box) and none of their corresponding networks were detecting the objects. I got 1 or 2 "hits", but those seemed to be hallucinations has they appeared for a single frame and were nowhere near the object.

What could be the cause of those really poor performances? Inadequate lighting? Not having the exact object? (I tried to get as close as possible, but I live in Quebec, so the writing is usually in french and there are slight design variation)

Thank you for your help, I've been pulling my hair for almost 2 weeks now.

**Comment by swapnesh-wani-nvidia** [comment]
Hello, could you please provide the rosbag recording and configuration files to reproduce this issue.

**Comment by jaiveersinghNV** [comment]
Hi @Maxime-Syc ,

We recently merged #23 which fixes some inconsistencies between the Python DOPE Training and Isaac ROS DOPE implementations.

Could you please take a look and see if the latest version of Isaac ROS DOPE corrects the issue you've observed?
