### ISSUE TITLE
Question about deformable convolution

### ISSUE THREAD

**Issue by Shaaa10** [NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation#4]
Hi, First of all Thank you.  I have one query.  Centre pose  uses Deformable convolution layer.  But in the "centerpose_pytorch2onnx.py"  script there is no Deformable convolution.  Does the converted ONNXmodel contain Deformable convolution layer ? Thank you .

**Comment by gordongrigor** [comment]
Yes.  The open source published version uses deformable convolutions, however this is hard to compile in Torch, and not supported at time of this Isaac ROS release in TensorRT, so we released a version replacing deformable convolutions with layers that are supported in TensorRT.
