### ISSUE TITLE
running Jetson orin NX

### ISSUE THREAD

**Issue by wengdunfang** [NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation#53]
Thank you for your work. Can the code run on Jetson Orin NX?

**Comment by Kaivalya192** [comment]
Hello there 
i am currently trying to impliment this foundation pose on jetson orin nx 
but it seems to have verry laggy and not working properly
were you able to impliment this?

**Comment by wengdunfang** [comment]
> Hello there i am currently trying to impliment this foundation pose on jetson orin nx but it seems to have verry laggy and not working properly were you able to impliment this?

In Jetson agx, I successfully run isaac_ros_foundationpose, but the effect is very poor. I don't think isaac_ros_foundationpose has been optimized yet. I suggest you use the GPU version directly.

**Comment by Kaivalya192** [comment]
@wengdunfang Thank you for your responce now i am trying to impliment [https://github.com/ammar-n-abbas/FoundationPoseROS2](this repo) but i am facing issue in building environment in jetson orin nx.
perticularly in conda environment.
can you help me?

**Comment by wengdunfang** [comment]
> @wengdunfang Thank you for your responce now i am trying to impliment [This repo](https://github.com/ammar-n-abbas/FoundationPoseROS2) but i am facing issue in building environment in jetson orin nx. perticularly in conda environment. can you help me?

my email: wengdunfang@qq.com，
